### ISSUE TITLE
What have I done wrong?

### ISSUE THREAD

**Issue by luma-vpk** [AveYo/ShowMMR#13]
Logged in! Launching DOTA...
GC is welcoming us. Version: 5765
Requesting 200 recent matches history
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Program.OnMatchHistory(IPacketGCMsg packetMsg) in C:\Users\luma\Downloads\ShowMMR-2023.07.23\ShowMMR_tool\Program.cs:line 342
   at Program.OnGCMessage(MessageCallback callback) in C:\Users\luma\Downloads\ShowMMR-2023.07.23\ShowMMR_tool\Program.cs:line 297
   at SteamKit2.Internal.Callback`1.Run(Object callback)
   at SteamKit2.CallbackManager.<>c__DisplayClass10_0.<Handle>b__1(CallbackBase callback)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Program.Main(String[] args) in C:\Users\luma\Downloads\ShowMMR-2023.07.23\ShowMMR_tool\Program.cs:line 126

**Comment by AveYo** [comment]
Game Coordinator has been mostly down these past hours, just look at Riyadh Masters having to pause game 2 between Spirit and Liquid for 30min+   
Reddit is probably full with people complaining about it  
So, just unlucky, you did nothing wrong.

**Comment by luma-vpk** [comment]
yo i fixed it, i open bat with opened dota and it works

**Comment by AveYo** [comment]
The tool works even if dota is not installed at all. 
The account must have played dota matches, and the game coordinator must be live ;)  
The error is about Callback i.e. the response from the game coordinator.  
It's been fixed on their end since you've posted, that's all
